# Generated by Django 4.2 on 2023-12-31 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contenido_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('sub_titulo', models.CharField(max_length=100, verbose_name='titulo')),
                ('descripcion', models.CharField(max_length=500, null=True, verbose_name='descripcion titulo')),
            ],
        ),
        migrations.CreateModel(
            name='menu_lateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='titulo')),
                ('descripcion', models.CharField(max_length=500, null=True, verbose_name='descripcion titulo')),
            ],
        ),
    ]
