# Generated by Django 4.2 on 2023-12-31 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_datospersonales_datospublicos_delete_menu_lateral'),
    ]

    operations = [
        migrations.CreateModel(
            name='contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoContenido', models.CharField(max_length=100, verbose_name='Categoria')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripcion')),
                ('fechaInicio', models.DateField(blank=True, null=True)),
                ('fechaFin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('nota', models.IntegerField(blank=True, null=True)),
                ('tipoNota', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo Nota')),
            ],
        ),
    ]
