# Generated by Django 4.2 on 2024-01-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_categoria', models.CharField(max_length=50, verbose_name='Codigo Categoria')),
                ('nombre', models.CharField(max_length=150, verbose_name='Categoria')),
            ],
        ),
    ]
