# Generated by Django 4.2 on 2024-01-01 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='tipoContenido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.categorias', verbose_name='Categoria'),
        ),
    ]
