# Generated by Django 4.2 on 2024-01-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_contenido_tipocontenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='empresa',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Empresa/Institucion'),
        ),
    ]
